const links = [
  {
    id: 101,
    title: "HTML Full Course for Beginners",
    url: "https://www.youtube.com/watch?v=qz0aGYrrlhU",
    description: "Learn HTML fundamentals from scratch.",
    link_type: "resources",
    og_title: "HTML Full Course for Beginners",
    og_description: "Complete HTML course for beginners.",
    og_image: "https://img.youtube.com/vi/qz0aGYrrlhU/maxresdefault.jpg",
    created_by: 1,
  },
  {
    id: 102,
    title: "HTML Forms and Input Tags",
    url: "https://www.youtube.com/watch?v=fNcJuPIZ2WE",
    description: "Learn forms and input elements in HTML.",
    link_type: "resources",
    og_title: "HTML Forms and Input Tags",
    og_description: "Build forms using HTML.",
    og_image: "https://img.youtube.com/vi/fNcJuPIZ2WE/maxresdefault.jpg",
    created_by: 1,
  },
  {
    id: 103,
    title: "CSS Full Course for Beginners",
    url: "https://www.youtube.com/watch?v=OXGznpKZ_sA",
    description: "Learn CSS from the basics.",
    link_type: "resources",
    og_title: "CSS Full Course for Beginners",
    og_description: "Complete CSS course for beginners.",
    og_image: "https://img.youtube.com/vi/OXGznpKZ_sA/maxresdefault.jpg",
    created_by: 1,
  },
  {
    id: 104,
    title: "CSS Flexbox Crash Course",
    url: "https://www.youtube.com/watch?v=3YW65K6LcIA",
    description: "Master CSS Flexbox layouts.",
    link_type: "resources",
    og_title: "CSS Flexbox Crash Course",
    og_description: "Learn Flexbox with practical examples.",
    og_image: "https://img.youtube.com/vi/3YW65K6LcIA/maxresdefault.jpg",
    created_by: 1,
  },
  {
    id: 105,
    title: "Responsive Web Design Tutorial",
    url: "https://www.youtube.com/watch?v=srvUrASNj0s",
    description: "Build responsive websites using CSS.",
    link_type: "resources",
    og_title: "Responsive Web Design Tutorial",
    og_description: "Learn responsive web design.",
    og_image: "https://img.youtube.com/vi/srvUrASNj0s/maxresdefault.jpg",
    created_by: 1,
  },
];

export default links;